imports:
  - { resource: "@SpipuConfigurationBundle/Resources/config/spipu_configuration.yaml" }
  - { resource: "@SpipuProcessBundle/Resources/config/spipu_configuration.yaml" }

spipu_configuration:
  app.website.name:
    type:     string
    required: true
    default:  "Website"

  test.field.password:
    type:     password
    required: true

  test.field.encrypted:
    type:     encrypted
    required: true
